Repository hello-nrfcloud/backend, pull requests merged in 2023-11, with the labels that each got.

#366 refactor: migrate to Node.JS test runner
  cdk/helpers/certificates/readFilesFromMap.spec.ts
  cdk/helpers/certificates/restoreCertificateFromSSM.spec.ts
  cdk/helpers/certificates/storeCertificateInSSM.spec.ts
  cdk/helpers/certificates/writeFilesFromMap.spec.ts
  cdk/helpers/lambdas/checkSumOfFiles.spec.ts
  cdk/helpers/lambdas/commonParent.spec.ts
  cdk/test-resources/checkMatchingQueryParams.spec.ts
  cellGeoLocation/SingleCellGeoLocationCache.spec.ts
  cellGeoLocation/cellId.spec.ts
  docker/compareSemanticVersions.spec.ts
  docker/compareSematicVerions.spec.ts
  docker/hashFolder.spec.ts
  docker/padVersion.spec.ts
  feature-runner/steps/parseMockRequest.spec.ts
  feature-runner/steps/parseMockResponse.spec.ts
  feature-runner/steps/toPairs.spec.ts
  historicalData/convertMessageToTimestreamRecords.spec.ts
  historicalData/getBinnedTime.spec.ts
  historicalData/getLocationQueryStatement.spec.ts
  historicalData/getLocationQueryStatement.ts
  historicalData/getSensorQueryStatement.spec.ts
  historicalData/getSensorQueryStatement.ts
  historicalData/getStartAndEndForType.spec.ts
  historicalData/normalizedData.spec.ts
  historicalData/paginateTimestreamQuery.spec.ts
  historicalData/transformTimestreamData.spec.ts
  kpis/dailyActiveDevices.spec.ts
  kpis/dailyActiveFingerprints.spec.ts
  nrfcloud/DeviceShadow.spec.ts
  nrfcloud/deviceShadowFetcher.spec.ts
  nrfcloud/deviceShadowRepo.spec.ts
  nrfcloud/getAccountInfo.spec.ts
  nrfcloud/getCurrentMonthlyCosts.spec.ts
  nrfcloud/test-data/deviceShadow.json
  nrfcloud/validatedFetch.spec.ts
  package-lock.json
  package.json
  util/checkMessageFromWebsocket.spec.ts
  util/createTrailOfCoordinates.spec.ts
  util/defer.spec.ts
  util/deg2rad.spec.ts
  util/getDistanceFromLatLngInKm.spec.ts
  util/hasValues.spec.ts
  util/hashSHA1.spec.ts
  util/isFirstElementInArrayNotEmpty.spec.ts
  util/settings.spec.ts
  util/slashless.spec.ts
  util/test/assertCall.ts
  util/ulid.spec.ts
  websocket/deviceShadowUpdateChecker.spec.ts
  websocket/deviceShadowUpdateChecker.ts
Labels: Refactoring

#374 test: using globstar to ignore dist and node_modules
  .github/workflows/run-unit-test-on-macos.yaml
  package-lock.json
  package.json
Labels: Refactoring

#376 ci: run unit test on macos on push
  .github/workflows/run-unit-test-on-macos.yaml
Labels: enhancement

#381 Fix coap measurement
  cdk/resources/containers/coap/src/handler.ts
  lambda/healthCheckForCoAP.ts
  util/parseDateTimeFromLogToTimestamp.spec.ts
  util/parseDateTimeFromLogToTimestamp.ts
Labels: Bug fix
